import{initializeApp}from"https://www.gstatic.com/firebasejs/10.13.1/firebase-app.js";
    import{browserLocalPersistence,browserSessionPersistence,createUserWithEmailAndPassword,deleteUser,getAuth,onAuthStateChanged,reload,sendEmailVerification,sendPasswordResetEmail,setPersistence,signInWithEmailAndPassword,signOut,updateProfile}from"https://www.gstatic.com/firebasejs/10.13.1/firebase-auth.js";
    import{doc,getDoc,getFirestore,serverTimestamp,setDoc}from"https://www.gstatic.com/firebasejs/10.13.1/firebase-firestore.js";
    import { firebaseConfig } from "./firebase-config.js";
    const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp),state={role:"orthophonist",registering:false,profile:null};
    const $=id=>document.getElementById(id),views=["loading","auth","pending","app"],cards=["loginCard","registerCard","childCard"];
    function showView(id){views.forEach(x=>$(x).classList.toggle("hidden",x!==id))}function showCard(id){cards.forEach(x=>$(x).classList.toggle("hidden",x!==id))}
    function notice(id,msg,type="info"){const box=$(id);box.textContent=msg||"";box.className="notice"+(msg?" show "+type:"")}
    function busy(id,on,working,normal){const b=$(id);b.disabled=on;b.textContent=on?working:normal}function clean(v){return String(v||"").trim()}
    function errorText(e){const map={"auth/email-already-in-use":"Cette adresse e-mail possède déjà un compte.","auth/invalid-credential":"Adresse e-mail ou mot de passe incorrect.","auth/invalid-email":"L’adresse e-mail n’est pas valide.","auth/too-many-requests":"Trop de tentatives. Réessayez dans quelques minutes.","auth/user-disabled":"Ce compte a été désactivé.","auth/weak-password":"Choisissez un mot de passe d’au moins 8 caractères.","auth/network-request-failed":"Connexion impossible. Vérifiez votre accès Internet.","permission-denied":"Les règles Firebase V2 ne sont pas encore publiées.","firestore/permission-denied":"Les règles Firebase V2 ne sont pas encore publiées."};return map[e?.code]||"Une erreur est survenue. Réessayez sans fermer la page."}
    function profileRef(uid){return doc(db,"notq_v2","app","users",uid)}async function getProfile(user){const snap=await getDoc(profileRef(user.uid));return snap.exists()?Object.assign({uid:snap.id},snap.data()):null}
    function setRole(role){state.role=role;document.querySelectorAll("[data-role]").forEach(b=>b.classList.toggle("active",b.dataset.role===role));if(role==="child"){showCard("childCard");return}showCard("loginCard");const parent=role==="parent";$("loginKicker").textContent=parent?"Espace famille":"Espace professionnel";$("loginTitle").textContent=parent?"Suivez ses progrès.":"Bon retour parmi nous.";$("loginIntro").textContent=parent?"Utilisez le compte créé depuis l’invitation de l’orthophoniste.":"Connectez-vous pour retrouver vos patients, vos séances et leurs progrès.";$("registerPrompt").classList.toggle("hidden",parent);notice("loginNotice","")}
    async function route(user){try{const profile=await getProfile(user);state.profile=profile;if(!profile){showView("auth");setRole("orthophonist");notice("loginNotice","Ce compte n’a pas encore de profil Notq V2.","error");return}if(profile.status==="pending"){resetPending();$("pendingName").textContent=profile.firstName||user.displayName||"Orthophoniste";$("pendingEmail").textContent=user.email||profile.email||"";$("emailStep").classList.toggle("done",user.emailVerified);$("emailStep").classList.toggle("current",!user.emailVerified);$("emailText").textContent=user.emailVerified?"Votre adresse e-mail est vérifiée.":"Ouvrez le message envoyé à votre adresse professionnelle.";showView("pending");return}if(profile.status==="rejected"||profile.status==="suspended"){resetPending();$("pendingName").textContent=profile.firstName||"Utilisateur";$("pendingEmail").textContent=user.email||"";$("statusTag").textContent=profile.status==="rejected"?"Demande refusée":"Compte suspendu";$("statusTitle").textContent=profile.status==="rejected"?"Votre demande n’a pas été validée.":"L’accès à ce compte est suspendu.";$("statusLead").textContent=profile.status==="rejected"?"Consultez le courriel envoyé par l’administrateur pour connaître la raison ou fournir les informations manquantes.":"Contactez l’administrateur Notq pour obtenir plus d’informations.";$("resend").classList.add("hidden");showView("pending");return}if(profile.status!=="active")throw new Error("unknown-status");const labels={super_admin:"Super administrateur",orthophonist:"Orthophoniste actif",parent:"Compte parent",child:"Compte enfant"};$("activeRole").textContent=labels[profile.role]||"Compte actif";$("welcomeTitle").textContent="Bienvenue, "+(profile.firstName||user.displayName||"utilisateur")+".";$("welcomeText").textContent=profile.role==="super_admin"?"Votre accès administrateur est reconnu. La gestion des demandes sera construite à la prochaine étape.":profile.role==="parent"?"Votre compte parent est actif. Les enfants reliés et leur progression seront ajoutés à l’étape suivante.":"Votre compte professionnel est actif. Les dossiers enfants seront ajoutés à l’étape suivante.";showView("app")}catch(e){console.error(e);showView("auth");notice("loginNotice",errorText(e),"error")}}
    function resetPending(){$("statusTag").textContent="Validation en cours";$("statusTitle").textContent="Votre demande est bien enregistrée.";$("statusLead").innerHTML="Bonjour <strong id=\"pendingName\">Orthophoniste</strong>. Votre espace restera protégé jusqu’à la vérification de vos justificatifs.";$("resend").classList.remove("hidden")}
    document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>setRole(b.dataset.role));document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const input=$(b.dataset.toggle),reveal=input.type==="password";input.type=reveal?"text":"password";b.textContent=reveal?"Masquer":"Afficher"});$("openRegister").onclick=()=>{notice("registerNotice","");showCard("registerCard")};$("backLogin").onclick=()=>showCard("loginCard");
    $("loginForm").onsubmit=async e=>{e.preventDefault();notice("loginNotice","");busy("loginSubmit",true,"Connexion…","Se connecter");try{await setPersistence(auth,$("remember").checked?browserLocalPersistence:browserSessionPersistence);const cred=await signInWithEmailAndPassword(auth,clean($("loginEmail").value).toLowerCase(),$("loginPassword").value),profile=await getProfile(cred.user);if(!profile){await signOut(auth);notice("loginNotice","Ce compte n’a pas encore de profil Notq V2.","error");return}if(state.role==="parent"&&profile.role!=="parent"){await signOut(auth);notice("loginNotice","Ce compte ne correspond pas à un espace parent.","error");return}if(state.role==="orthophonist"&&!['orthophonist','super_admin'].includes(profile.role)){await signOut(auth);notice("loginNotice","Ce compte ne correspond pas à un espace professionnel.","error");return}await route(cred.user)}catch(err){console.error(err);notice("loginNotice",errorText(err),"error")}finally{busy("loginSubmit",false,"Connexion…","Se connecter")}};
    $("registerForm").onsubmit=async e=>{e.preventDefault();notice("registerNotice","");if($("registerPassword").value.length<8){notice("registerNotice","Le mot de passe doit contenir au moins 8 caractères.","error");return}busy("registerSubmit",true,"Envoi de la demande…","Envoyer ma demande");state.registering=true;let cred=null,profileSaved=false,emailWarning=false;try{await setPersistence(auth,browserLocalPersistence);const email=clean($("registerEmail").value).toLowerCase();cred=await createUserWithEmailAndPassword(auth,email,$("registerPassword").value);const first=clean($("firstName").value),last=clean($("lastName").value);await updateProfile(cred.user,{displayName:first+" "+last});const profile={firstName:first,lastName:last,fullName:first+" "+last,email,phone:clean($("phone").value),workplace:clean($("workplace").value),wilaya:clean($("wilaya").value),commune:clean($("commune").value),role:"orthophonist",status:"pending",registrationSource:"public_form",documentsMethod:"email",createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(profileRef(cred.user.uid),profile);profileSaved=true;try{await sendEmailVerification(cred.user)}catch(mailError){console.error(mailError);emailWarning=true}state.profile=profile;await route(cred.user);if(emailWarning)notice("pendingNotice","Le compte est enregistré, mais l’e-mail n’a pas pu être envoyé. Utilisez le bouton Renvoyer l’e-mail.","info")}catch(err){console.error(err);if(cred&&!profileSaved){try{await deleteUser(cred.user)}catch(cleanupError){console.error(cleanupError);await signOut(auth)}}notice("registerNotice",errorText(err),"error")}finally{state.registering=false;busy("registerSubmit",false,"Envoi de la demande…","Envoyer ma demande")}};
    $("forgot").onclick=async()=>{const email=clean($("loginEmail").value).toLowerCase();if(!email){notice("loginNotice","Saisissez d’abord votre adresse e-mail.","info");$("loginEmail").focus();return}try{await sendPasswordResetEmail(auth,email);notice("loginNotice","Un lien de réinitialisation vient d’être envoyé.","success")}catch(e){notice("loginNotice",errorText(e),"error")}};
    $("childForm").onsubmit=e=>{e.preventDefault();notice("childNotice","Le code enfant sera activé avec les dossiers patients à l’étape 2.","info")};$("resend").onclick=async()=>{try{await sendEmailVerification(auth.currentUser);notice("pendingNotice","L’e-mail de vérification a été renvoyé.","success")}catch(e){notice("pendingNotice",errorText(e),"error")}};$("refresh").onclick=async()=>{if(!auth.currentUser)return;busy("refresh",true,"Vérification…","Vérifier mon statut");try{await reload(auth.currentUser);await route(auth.currentUser);if(state.profile?.status==="pending")notice("pendingNotice","Le compte est toujours en cours de validation.","info")}catch(e){notice("pendingNotice",errorText(e),"error")}finally{busy("refresh",false,"Vérification…","Vérifier mon statut")}};
    async function logout(){await signOut(auth);state.profile=null;showCard("loginCard");showView("auth")}$("pendingLogout").onclick=logout;$("appLogout").onclick=logout;onAuthStateChanged(auth,async user=>{if(state.registering)return;if(!user){showView("auth");setRole(state.role);return}await route(user)});
  